### ISSUE TITLE
C-Mannosylation on tryptophan

### ISSUE THREAD

**Issue by yongwangCPH** [salilab/allosmod-lib#1]
I am trying to find a tool to glycosylate my protein which contains different types of glycosylation, including some unusual C-Mannosylation on tryptophan. Does allosmod support it? Thanks!

**Comment by benmwebb** [comment]
AllosMod currently only supports attachment to the sugar O1 atom, sorry: https://modbase.compbio.ucsf.edu/allosmod/help.cgi?type=glyc

To make it work for C-mannosylation you'd (at a minimum) need to add suitable PRES entries for the topology to https://github.com/salilab/allosmod-lib/blob/master/data/top_all_glyco.lib - not impossible but not a trivial task.
